version: "3.7"
services:
  quote-gen:
    build: ./quote_gen
    image: quote-gen-service
    deploy:
      replicas: 2
    ports:
      - "5000-5005:5000"
    volumes:
      - ./quote_gen:/app
  quote-disp:
    build: ./quote_disp
    image: quote-disp-service
    deploy:
      replicas: 2
    ports:
      - "5006-5010:5001"
    depends_on:
      - quote-gen
    volumes:
      - ./quote_disp:/app