version: "3.7"
services:
  quote-gen:
    build: ./quote_gen
    container_name: quote-gen-container
    ports:
      - "5000:5000"
  quote-disp:
    build: ./quote_disp
    container_name: quote-disp-container
    ports:
      - "5001:5001"
    depends_on:
      - quote-gen